anpdko/i-will-help-you-client

src/components/ProjectHeader/ProjectHeader.module.scss, src/components/ProjectHeader/ProjectHeader.tsx, src/data/projectHeaderData.ts, src/pages/AboutPage/AboutPage.tsx, src/pages/ProjectsPage/ProjectsPage.tsx, src/styles/index.css, src/styles/scss/mixins.scss, src/translation/i18n.ts
=> HELPYOU-26--Project-page-ProjectHeader-component

src/components/Translation/Translation.module.scss
=> HELPYOU-39-translation.animation

src/components/Navbar/Navbar.module.scss, src/components/Navbar/Navbar.tsx, src/components/Reviews/Reviews.tsx, src/components/UI/ButtonApp/ButtonApp.module.scss, src/components/Volunteer/Volunteer.module.scss, src/components/Volunteer/Volunteer.tsx, src/main.tsx, src/services/admin/header.service.ts, src/store/reviews/reviewsSlice.ts, src/store/reviews/reviewsType.ts, src/store/store.ts
- Made an adaptation for Volunteer
- fix Button App style
- fixed bugs in Navbar and adapted a little
=> HELPYOU-35--Volunteer

src/components/Projects/Project/Project.module.scss, src/components/Projects/Project/Project.tsx, src/components/Projects/Projects.module.scss, src/components/Projects/Projects.tsx, src/styles/index.scss
Add adaptive for project item in Projects components.
Add adaptive font-size for h1, h2 and p.
=> Add adaptive for projects

src/components/About/About.module.scss, src/components/About/About.tsx, src/components/About/AboutItem/AboutItem.module.scss, src/components/About/AboutItem/AboutItem.tsx, src/hooks/useWindowWidth.ts
Add adaptability for component.
Add the useWindowWidth hook to track changes in screen resolution.
Change class names in the AboutItem component.
Refactor code style.
=> Add adaptive for about component

package-lock.json, package.json, vite.config.ts
Add plugin vite-plugin-image-optimizer for optimization image during build project.
Before:
After:
Result:
=> feat: add plugin for optimization image

src/components/Footer/Footer.module.scss, src/components/Footer/Footer.tsx
Пофіксила стилі футера. Адаптив футера в процесі.
=> Helpyou 8  footer components

src/components/Navbar/Navbar.module.scss, src/components/admin/NavbarAdmin/NavbarAdmin.tsx, src/pages/admin/AuthAdminPage/AuthAdminPage.tsx, src/routes/RoutesAdmin.tsx, src/services/admin/admin.service.ts, src/store/admin/adminSlice.ts, src/styles/index.scss
create active link color + run format
=> HELPYOU-55--active-Navbar

src/components/FAQ/FAQ.tsx, src/components/Navbar/Navbar.module.scss, src/components/ReadyNeedHeader/ReadyNeedHeader.tsx, src/components/UI/InputApp/InputApp.tsx, src/components/UI/SelectApp/SelectApp.tsx, src/components/UI/TextareaApp/TextareaApp.tsx, src/components/UI/index.ts, src/components/admin/NavbarAdmin/NavbarAdmin.module.scss, src/components/admin/NavbarAdmin/NavbarAdmin.tsx, src/components/index.ts, src/pages/ReadyHelpPage/ReadyHelpPage.tsx, src/pages/admin/ProjectsAdminPage/ProjectsAdminPage.tsx, src/routes/RoutesAdmin.tsx
Закомітився і пулл реквест, вибачаюсь, буду уважніша)
=> navbar admin

src/components/FAQ/FAQItem/FAQItem.tsx, src/components/Navbar/Navbar.module.scss, src/components/UI/InputFormApp/InputFormApp.tsx, src/components/UI/TextareaFormApp/TextareaFormApp.tsx, src/components/admin/NavbarControlAdmin/NavbarControlAdmin.tsx, src/components/admin/index.ts, src/pages/admin/ReviewsAdminPage/ReviewsAdminPage.tsx, src/pages/admin/ReviewsAdminPage/TableReviewsAdmin.tsx, src/pages/admin/ReviewsCreateAdminPage/ReviewsCreateAdminPage.tsx, src/pages/admin/ReviewsEditAdminPage/ReviewsEditAdminPage.tsx, src/pages/admin/index.ts, src/routes/RoutesAdmin.tsx, src/store/reviews/reviewsSlice.ts
=> fix burger  transform

src/components/Banners/Bunner/Banner.module.scss, src/components/Banners/Bunner/Banner.tsx
- I made a link to the entire banner card
=> I made a link to the entire banner card

src/components/form/FormDonation/FormDonation.module.scss, src/components/form/FormDonation/PaymentBlock/PaymentBlock.module.scss, src/components/form/FormDonation/PaymentBlock/PaymentBlock.tsx, src/components/form/FormDonation/PaymentForm/ChooseProject.tsx, src/components/form/FormDonation/PaymentForm/PaymentForm.module.scss, src/components/form/FormDonation/RadioInput/RadioInput.module.scss, src/components/form/FormDonation/RadioInput/RadioInput.tsx, src/components/form/FormNeedHelp/TypeOfAssistance/CheckboxSelect.tsx, src/components/form/FormNeedHelp/TypeOfAssistance/TypeOfAssistance.module.scss, src/components/form/FormNeedHelp/TypeOfAssistance/TypeOfAssistance.tsx, src/styles/mixins.scss
Add decorative line to forms.
Correct the style according to the design.
Clean code after fix.
Disable the Transfer and Crypto buttons.
=> Helpyou 112  fix style form donation

src/components/form/Comment/Comment.module.scss, src/components/form/FormDonation/DonateStuff/DonateStuff.module.scss, src/components/form/FormDonation/FormDonation.module.scss, src/components/form/FormDonation/PaymentBlock/PaymentBlock.module.scss, src/components/form/FormDonation/PaymentForm/PaymentForm.module.scss, src/components/form/FormDonation/RadioInput/RadioInput.module.scss, src/components/form/FormNeedHelp/Files/Files.module.scss, src/components/form/FormNeedHelp/FormNeedHelp.module.scss, src/components/form/FormNeedHelp/TypeOfAssistance/TypeOfAssistance.module.scss, src/components/form/FormReadyHelp/DaysOfVolunteering/DaysOfVolunteering.module.scss, src/components/form/FormReadyHelp/FormReadyHelp.module.scss, src/components/form/FormReadyHelp/Language/Language.module.scss, src/components/form/FormReadyHelp/SelectCountry/SelectCountry.module.scss, src/components/form/FormReadyHelp/Skills/Skills.module.scss, src/components/form/FormReadyHelp/SocialNetwork/SocialNetwork.module.scss, src/components/form/PhoneNumber/PhoneNumber.module.scss, src/components/wrapper/FormWrapper/FormWrapper.module.scss, src/styles/index.scss, src/styles/mixins.scss, src/translation/ua.json
Fix adaptive styles for forms (ready to help, need help, donation).
=> Fix adaptive in forms

src/components/FAQ/FAQ.module.scss, src/components/FAQ/FAQ.tsx, src/components/FAQ/FAQItem/FAQItem.module.scss, src/components/FAQ/FAQItem/FAQItem.tsx, src/components/UI/InputFormApp/InputFormApp.module.scss, src/components/UI/form/SelectInput/selectStyle.ts, src/components/form/Comment/Comment.module.scss, src/components/form/FormDonation/DonateStuff/DonateStuff.module.scss, src/components/form/FormDonation/FormDonation.module.scss, src/components/form/FormDonation/PaymentForm/PaymentForm.module.scss, src/components/form/FormNeedHelp/Files/Files.module.scss, src/components/form/FormNeedHelp/FormNeedHelp.module.scss, src/components/form/FormNeedHelp/TypeOfAssistance/TypeOfAssistance.module.scss, src/components/form/FormReadyHelp/DaysOfVolunteering/DaysOfVolunteering.module.scss, src/components/form/FormReadyHelp/DaysOfVolunteering/DaysOfVolunteering.tsx, src/components/form/FormReadyHelp/FormReadyHelp.module.scss, src/components/form/FormReadyHelp/Language/Language.module.scss, src/components/form/FormReadyHelp/SelectCountry/SelectCountry.module.scss, src/components/form/FormReadyHelp/Skills/Skills.module.scss, src/components/form/FormReadyHelp/Skills/Skills.tsx, src/components/form/FormReadyHelp/SocialNetwork/SocialNetwork.module.scss, src/components/form/PhoneNumber/PhoneNumber.module.scss, src/components/wrapper/FormWrapper/FormWrapper.module.scss, src/pages/NeedHelpPage/NeedHelpPage.tsx
previous deploy  =>    https://sparkly-lebkuchen-addf58.netlify.app/
=> Fix for adaptive style

src/components/form/FormReadyHelp/DaysOfVolunteering/DaysOfVolunteering.module.scss, src/components/form/FormReadyHelp/DaysOfVolunteering/DaysOfVolunteering.tsx, src/components/form/FormReadyHelp/Language/Language.module.scss, src/components/form/FormReadyHelp/Language/Language.tsx, src/translation/ua.json
Fix delete btn in language and days of volunteering in form.
=> Fix form: fix delete btn

src/components/form/FormReadyHelp/SocialNetwork/SocialNetwork.scss, src/components/form/FormReadyHelp/SocialNetwork/SocialNetwork.tsx, src/components/icons/WhatsAppIcon.tsx, src/translation/ua.json
Change Viber to WhatsApp.
Add validation to social networks input.
Add style to social networks component.
=> Fix form: add validation to social networks

src/components/form/FormReadyHelp/SocialNetwork/SocialNetwork.tsx, src/translation/ua.json
Fix validation and error message for telegram and instagram inputs.
=> Fix form: fix validation and error message in social networks

src/components/LazyImage/LazyImage.tsx, src/components/Reviews/ReviewsDesktop/ReviewsDesktop.tsx
Зменшила радіус бо були виступи в банерах
=> fix skeleton border

src/components/form/FormReadyHelp/DaysOfVolunteering/DaysOfVolunteering.module.scss, src/components/form/FormReadyHelp/Language/Language.module.scss, src/components/form/PhoneNumber/PhoneNumber.scss
Add focus to input with flags.
Add focus to add and remove buttons in days of volunteering and languages fields.
=> Fix focus effect

src/components/UI/ArticleSection/ArticleSection.module.scss, src/components/UI/ArticleSection/ArticleSection.tsx, src/components/about/About/About.module.scss, src/components/about/About/AboutItem/AboutItem.module.scss, src/components/about/AboutDocuments/AboutDocuments.module.scss, src/components/about/AboutTeam/AboutTeam.module.scss, src/components/projects/ProjectHeader/ProjectHeader.module.scss, src/components/projects/ProjectHeader/SlideAbout/SlideAbout.module.scss, src/components/projects/ProjectHeader/SlideAbout/SlideAbout.tsx, src/data/aboutTeamData.ts, src/store/projects/projectsType.ts, src/translation/ua.json
Pre-deploy  https://sparkly-lebkuchen-addf58.netlify.app/
=> Helpyou  dmytro kuts  branch
